[package]
name = "mosaic-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
base64 = "0.22.1"
borsh = "1.6.0"
clap = { version = "4.5.31", features = ["derive"] }
mosaic = { path = "../mosaic" }
pinocchio = "0.10.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
shellexpand = "3.1.2"
solana-account = "3.4.0"
solana-account-decoder-client-types = "3.1.12"
solana-commitment-config = "3.1.1"
solana-instruction = "3.3.0"
solana-keypair = "3.1.2"
solana-pubkey = { version = "4.1.0", features = ["curve25519"] }
solana-rpc-client = "3.1.12"
solana-rpc-client-types = "3.1.12"
solana-sdk-ids = "3.1.0"
solana-signer = "3.0.0"
solana-transaction = "3.1.0"
